- block:
  - name: Get id
    shell: id
    changed_when: False
    failed_when: False
    register: result
  - debug:
      msg: "{{ result.stdout }}"
    tags:
      - never
      - print_info
  - block: 
    - shell: env
      register: result
      changed_when: False
    - debug:
        msg: "{{ result.stdout }}"
    tags:
      - never
      - print_debug
  ignore_errors: true