
    sudo mkdir -p /etc/rancher/k3s/
    sudo chmod -R 777 /etc/rancher
    cp k3s/config.yaml /etc/rancher/k3s/
    sudo swapoff -a
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik" INSTALL_K3S_SKIP_ENABLE=true INSTALL_K3S_SKIP_START=true sh -s - server
