- name: DNF packages
  set_fact:
    dnf_packages:
      - vim
      - google-chrome-stable
      - git
      - openssl
      - containerd
      - kernel-devel
      - kernel-headers
      - kernel-tools
      - etcd
      - python3-pip

- name: Install dnf packages
  dnf:
    name: "{{ dnf_packages }}"
    state: present
  become: true
