---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory # Staging
    # server: https://acme-v02.api.letsencrypt.org/directory # Production
    email: your-email@email.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
      - http01:
          ingress:
            class: nginx


# Example usage
#
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: my-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
# spec:
#   rules:
#     - host: example.com
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: my-service
#               servicePort: 80
#   tls:
#     - hosts:
#       - example.com

###

# Example Cert
#
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: example-cert  #name of this object
#   namespace: default #same namespace as 
# spec:
#   dnsNames:
#     - example.com
#   secretName: example-tls-cert
#   issuerRef:
#     name: letsencrypt-cluster-issuer
#     kind: ClusterIssuer

# Example Usage
#
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: my-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   tls:
#   - hosts:
#     - example.com
#   secretName: example-tls-cert
#   rules:
#   - host: example.com
#     http:
#       paths:
#         - path: /
#           pathType: Exact
#           backend:
#             service:
#               name: backend-service
#               port:
#                 number: 80
