#!/usr/bin/env bash
# NOTE: This file is automatically generated!
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd ${SCRIPT_DIR}/..
CHART_SELECTOR=hashicorp
CHART_NAME=consul
CHART_URL=https://helm.releases.hashicorp.com
./scripts/get_helm.sh \
  ${CHART_SELECTOR} \
  ${CHART_NAME} \
  ${CHART_URL}
