---
# Source: jaeger/templates/cassandra-schema-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: jaeger-cassandra-schema
  labels:
    helm.sh/chart: jaeger-0.65.5
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: jaeger
    app.kubernetes.io/version: "1.39.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: cassandra-schema
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: jaeger-cassandra-schema
    spec:
      securityContext:
        {}
      serviceAccountName: jaeger-cassandra-schema
      containers:
      - name: jaeger-cassandra-schema
        image: jaegertracing/jaeger-cassandra-schema:1.39.0
        imagePullPolicy: IfNotPresent
        securityContext:
          {}
        env:
          
          - name: CASSANDRA_SERVERS
            value: jaeger-cassandra
          - name: CASSANDRA_PORT
            value: "9042"
          
          - name: CASSANDRA_KEYSPACE
            value: jaeger_v1_test
          - name: CASSANDRA_USERNAME
            value: user
          - name: CASSANDRA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jaeger-cassandra
                key: password
          - name: CQLSH_HOST
            value: jaeger-cassandra
          
          - name: DATACENTER
            value: "dc1"
          - name: KEYSPACE
            value: jaeger_v1_test
        resources:
          {}
        volumeMounts:
      restartPolicy: OnFailure
      volumes:
