#!/usr/bin/env bash
# NOTE: This file is automatically generated!
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd ${SCRIPT_DIR}/..
CHART_SELECTOR=kubernetes-dashboard
CHART_NAME=kubernetes-dashboard
CHART_URL=https://kubernetes.github.io/dashboard/
./scripts/get_helm.sh \
  ${CHART_SELECTOR} \
  ${CHART_NAME} \
  ${CHART_URL}
