---
# apiVersion: traefik.containo.us/v1alpha1
# kind: IngressRoute
# metadata:
#   name: keycloak-ingress
#   labels:
#     method: traefik
#   annotations:
#     kustomize: "true"
# spec:
#   entryPoints:
#   - web
#   # - https
#   - http-management
#   routes:
#   - kind: Rule
#     match: Host(`keycloak.themachine`)
#     services:
#     - kind: Service
#       name: keycloak-http
# ---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak-ingress
  namespace: default
  labels:
    method: traefik
  annotations:
    kustomize: "true"
spec:
  entryPoints:
  - websecure
  - web
  routes:
  - match: Host(`keycloak.themachine`) || Host(`keycloak-http`)
    kind: Rule
    services:
    - name: keycloak-http
      kind: Service
      port: 80