---
# Source: traefik/templates/deployment.yaml
- op: replace
  path: /spec/template/spec/containers/0/args
  value:
    - "--accesslog=true"
    - "--global.checknewversion"
    - "--global.sendanonymoususage"
    - "--entrypoints.metrics.address=:9100/tcp"
    - "--entrypoints.traefik.address=:9000/tcp"
    - "--entrypoints.web.address=:8000/tcp"
    - "--entrypoints.websecure.address=:8443/tcp"
    - "--api.dashboard=true"
    - "--ping=true"
    - "--metrics.prometheus=true"
    - "--metrics.prometheus.entrypoint=metrics"
    - "--providers.kubernetescrd"
    - "--providers.kubernetesingress"
    - "--entrypoints.websecure.http.tls=true"
