---
# Source: artifactory/templates/artifactory-binarystore-secret.yaml
kind: Secret
apiVersion: v1
metadata:
  name: artifactory-binarystore
  labels:
    app: artifactory
    chart: artifactory-107.49.3
    heritage: Helm
    release: artifactory
stringData:
  binarystore.xml: |-
    <!-- File system filestore -->
    <config version="v1">
        <chain> <!--template="file-system"-->
                <provider id="file-system" type="file-system"/>
        </chain>
    </config>
