
- name: Install repo
  become: yes
  yum_repository:
    name: code
    description: Visual Studio Code repo
    file: vscode
    baseurl: 'https://packages.microsoft.com/yumrepos/vscode'
    gpgkey: 'https://packages.microsoft.com/keys/microsoft.asc'
    gpgcheck: yes

- name: Install package
  become: yes
  dnf:
    name: code
    state: present
