- name: Create ansible user
  user:
    name: ansible
    state: present
  become: true
  become_user: root

- name: Allow ansible user to run sudo without a password
  lineinfile:
    path: /etc/sudoers
    line: 'ansible ALL=(ALL) NOPASSWD:ALL'
    state: present
    validate: '/usr/sbin/visudo -cf %s'
  become: true
  become_user: root

- name: setup ssh as ansible user
  become: true
  become_user: ansible
  block:
  - name: create .ssh
    ansible.builtin.file:
      path: /home/ansible/.ssh/
      state: directory
      owner: ansible
      mode: 0700
  - name: Generate SSH key pair
    community.crypto.openssh_keypair:
      type: rsa
      path: /home/ansible/.ssh/id_rsa
      owner: ansible
      mode: 0600
  - name: Get public key
    slurp:
      src: /home/ansible/.ssh/id_rsa.pub
    register: pub_key
  # - name: add localhost to known_hosts
  #   known_hosts:
  #     path: /home/ansible/.ssh/known_hosts
  #     name: "{{ ansible_fqdn }}"
  #     key: "localhost {{ pub_key['content'] | b64decode }}"
  - name: Set authorized key
    authorized_key:
      user: ansible
      state: present
      key: "{{ pub_key['content'] | b64decode }}"
