---
# Source: fluentd/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  labels:
    helm.sh/chart: fluentd-0.3.9
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/version: "v1.14.6"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluentd
      app.kubernetes.io/instance: fluentd
  template:
    metadata:
      annotations:
        checksum/config: 80ee071baced48f18da871108d21ff9bfe0771cc8e08d6cb6b824cadc3f3d62f
      labels:
        app.kubernetes.io/name: fluentd
        app.kubernetes.io/instance: fluentd
    spec:
      
      serviceAccountName: fluentd
      securityContext:
        {}
      containers:
        - name: fluentd
          securityContext:
            {}
          image: "fluent/fluentd-kubernetes-daemonset:v1.14.6-debian-elasticsearch7-1.0"
          imagePullPolicy: IfNotPresent
          env:
            - name: FLUENTD_CONF
              value: ../../../etc/fluent/fluent.conf
          ports:
          - name: metrics
            containerPort: 24231
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
              {}
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
              readOnly: true
            - mountPath: /etc/fluent
              name: etcfluentd-main
            - mountPath: /etc/fluent/config.d/
              name: etcfluentd-config
            - name: fluentd-custom-cm-fluentd-prometheus-conf
              mountPath: /etc/fluent/fluentd-prometheus-conf.d
      volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
        - configMap:
            defaultMode: 511
            name: fluentd-main
          name: etcfluentd-main
        - configMap:
            defaultMode: 511
            name: fluentd-config
          name: etcfluentd-config
        - name: fluentd-custom-cm-fluentd-prometheus-conf
          configMap:
            name: fluentd-prometheus-conf
            defaultMode: 0777
