---
# Source: fluentd/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  labels:
    helm.sh/chart: fluentd-0.3.9
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/instance: fluentd
    app.kubernetes.io/version: "v1.14.6"
    app.kubernetes.io/managed-by: Helm
